# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-02 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc', models.UUIDField(default=uuid.uuid4, verbose_name='UUID code')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='created in')),
                ('used_in', models.DateTimeField(blank=True, null=True, verbose_name='used in')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
